spring:
  application:
    name: dscommerce

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET:tu7crHR4UON64BQQtCeIvRnkaHcgzmLcp6CtwHel9ficDZ/z0rl7b0jLdjR3gFnndBoJAPcpKZ8CYS2FLVNUUA==}

  # Access Token
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:600000} # 10 minutos (ms)

  # Refresh Token
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 dias (ms)

#flyway:
  #enabled: true
  #baseline-on-migrate: true